---
title: "Untitled"
output: html_document
date: "2022-12-27"
editor_options: 
  chunk_output_type: inline
---


# load libraries
```{r}
library(pacman)
p_load(tidyverse, magrittr, dplyr, plyr, data.table,
       lubridate, janitor, ggplot2, zoo, roll, R.utils,
       mclust,
       av, seewave, tuneR, phonTools, soundgen, # acoustic analysis
       foreach, doParallel # parallel processing
       )
op <- options(digits.secs=3)
```

# do parallel
```{r}
cores=detectCores()
cl <- makeCluster(cores[1]-40) #not to overload your computer
registerDoParallel(cl)
```


# create wave
## Pteropus lylei

```{r}
path <- "../../../../Dropbox/MPI/Pteropus/data/"
studies <- list.files(path, pattern = "*.csv", 
                      full.names = FALSE)
layout(1)
k = 2
time_offset <- 7*3600
sampling_rate <- 18.74
for(k in 2:length(studies)){
  df <- fread(paste0(path,studies[k])) %>% clean_names()
  bats <- unique(df$tag_local_identifier)
  plot(df$location_long, df$location_lat, asp = 1, col = df$tag_local_identifier)
  # df$timestamp %>% ymd_hms %>% date %>% table
  j = 1
  for(j in 1:length(bats)){
    bat <- df[df$tag_local_identifier == bats[j],]
    with(bat[bat$sensor_type == "gps",], 
         plot(timestamp, ground_speed, col = date(timestamp)))
    dates <- bat$timestamp %>% ymd_hms %>% date %>% unique  
    i=1
    for(i in 1:length(dates)){
     d <- bat[which(date(ymd_hms(bat$timestamp)) == dates[i] & bat$sensor_type == "acceleration"),]
      if(nrow(d) > 100){
        db <- foreach(ii = 1:nrow(d), .combine = rbind) %dopar% {
          require(magrittr)
          temp <- {}
          x <- NA
          y <- NA
          z <- NA
          time <- NA
          burst <- NA
          temp <- d$eobs_accelerations_raw[ii] %>% strsplit(" ") %>% 
            unlist %>% 
            as.numeric
          if(length(temp) > 0){
            x <- temp[seq(1, length(temp), 3)]
            y <- temp[seq(2, length(temp), 3)]
            z <- temp[seq(3, length(temp), 3)]
            temp_time <- seq.POSIXt(from = d$timestamp[ii], 
                                     to = d$timestamp[ii]+length(temp)/sampling_rate/3, 
                                     length.out = length(temp)/3)
            time <- format(temp_time, "%Y-%m-%d %H:%M:%OS3") %>% as.character
            burst <- rep(ii, length(temp))
          }
          temp <- data.frame(x,y,z,time,burst)
        }
      db <- na.omit(db)
      db$time <- ymd_hms(db$time)
      # remove points after sunrise
      # db <- db[#db$time > ymd_hms(paste0(dates[j]-1, " ", "23:00:00")) &
      #         db$time < ymd_hms(paste0(dates[i], " ", "12:00:00")),]
      # db <- db[hour(db$time) < 12 | hour(db$time) > 22,]
      png(filename = paste0(path, "wingbeat/", studies[k], bats[j], "_", dates[i],"_z_by_time.png"),
          width = 1000, height = 600)
        layout(rbind(1:2))
        plot(ymd_hms(db$time)+time_offset, db$z, pch = 16, type = "o", main = bats[j],
             xlab = "local time", ylab = "Z", cex = 0.1,
             col = rgb(0,
                      (length(db$z):1)/length(db$z),
                      (1:length(db$z))/length(db$z),
                      1))
        try({with(bat[date(bat$timestamp) == dates[i],], 
             plot(location_long, location_lat, 
                  type = "o", pch = 16, asp = 1,
                  xlab = "Longitude", ylab = "Latitude",
                  col = rgb(0,
                            (length(event_id):1)/length(event_id),
                            (1:length(event_id))/length(event_id),
                            1)))
        })
      dev.off()
    
      w <- Wave(left = db$z, samp.rate = sampling_rate, bit = 16)
      # plot(w)
      spectro(w)
      wf <- ffilter(w, f= sampling_rate, from = 2, to = 4, bandpass = TRUE)
      
      png(filename = paste0(path, "wingbeat/", studies[k], bats[j], "_", dates[i],"_wingbeatfreq.png"))
        spectro(wf, f = sampling_rate, wl = 1024*4, ovlp = 75, fastdisp = TRUE)
        par(new=TRUE)
        pf <- dfreq(wf, f=sampling_rate, wl = 1024*4, ovlp=75, threshold=30, 
                    type="l", col="red", lwd=0.5, xlab = "", ylab = "")  
      dev.off()
      layout(1)
    
      # get periods where wing beat can be estimated
      idx <- which(!is.na(pf[,2]))
      stable_var <- seqToIntervals(idx) %>% as.data.frame
      stable_var$length <- stable_var$to - stable_var$from + 1
      
      ## create 
      # multiply by sampling interval of pf
      w_stable <- stable_var * (pf[2,1])
      df_stable <- stable_var * (pf[2,1]) * sampling_rate
      
     try({
        w_stable$peak_freq <- NA
        w_stable$peak_amp <- NA
        w_stable$amplitude <- NA
        jj = 1
        for(jj in 1:nrow(w_stable)){
          if(stable_var$length[jj] > 1){
            w_cut <- Wave(left = db$z[df_stable$from[jj]:df_stable$to[jj]] %>% na.omit, 
                          samp.rate = sampling_rate, bit = 16)
            plot(w_cut)
            wf_cut <- ffilter(w_cut, f= sampling_rate, from = 2, to = 4, bandpass = TRUE)
            spectro(wf_cut, f = sampling_rate)
            spec <- meanspec(wf_cut, f=sampling_rate, plot = TRUE)
            peak <- fpeaks(spec, nmax = 8)
            pidx <- which(peak[,1] > 0.0025) 
            midx <- which.max(peak[pidx,2])
            w_stable$peak_freq[jj] <- peak[pidx[midx],1]
            w_stable$peak_amp[jj] <- peak[pidx[midx],2]  
            # df$ACCZ[df_stable$from[i]:df_stable$to[i]] %>% hist
            maxz <- roll_max(db$z[df_stable$from[jj]:df_stable$to[jj]], width = 6) %>%
              median(na.rm = TRUE)
            minz <- roll_min(db$z[df_stable$from[jj]:df_stable$to[jj]], width = 6) %>%
              median(na.rm = TRUE)
            # abline(v = c(minz, maxz), col = 2, lty = 2)
            w_stable$amplitude[jj] <- maxz - minz 
          }
        }
     }) 
      try({
        png(filename = paste0(path, "wingbeat/", studies[k], bats[j], "_", dates[i],"_domfreq_segments.png"))
          plot(x = ymd_hms(db$time[df_stable$from])+time_offset, y = w_stable$peak_freq*1000, 
             cex = 2*scales::rescale(w_stable$amplitude), 
             xlab = "local time", ylab = "dominant wingbeat frequency (Hz)")
          segments(x0 = ymd_hms(db$time[df_stable$from])+time_offset, 
              y0 = w_stable$peak_freq*1000, 
              x1 = ymd_hms(db$time[df_stable$to])+time_offset, 
              y1 = w_stable$peak_freq*1000)
        dev.off()  
      })
      
    save(db,w,wf,pf, sampling_rate, stable_var, w_stable, df_stable, 
         file = paste0(path, "wingbeat/", studies[k], bats[j], "_", dates[i],"_wingbeatfreq.robj"))
      
    } 
    }
    }
  }


```
